@baseURL=http://127.0.0.1:3333

### Health Check
GET {{baseURL}}/health-check


### create an new user
POST {{baseURL}}/create-user
Content-Type: application/json

{
    "name": "kellton",
    "email":"kell@gmail.com",
    "password": "123456"
}